# Generated by Django 5.0.14 on 2026-08-11 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('STAGE_CHANGE', 'Stage Changed'), ('TEMPERATURE_CHANGE', 'Temperature Changed'), ('ASSIGNMENT', 'Assignment Changed'), ('FOLLOWUP', 'Follow-up'), ('NOTE', 'Note Added'), ('ADMISSION', 'Admission'), ('PAYMENT', 'Payment'), ('SYSTEM', 'System Event')], max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(db_index=True)),
                ('followup_time', models.TimeField(blank=True, null=True)),
                ('followup_mode', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('VISIT', 'Visit'), ('OTHER', 'Other')], default='CALL', max_length=10)),
                ('followup_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('NOT_CONNECTED', 'Not Connected'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_from_excel', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
            ],
            options={
                'ordering': ['-followup_date', '-followup_time'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
