# Generated by Django 6.0.6 on 2026-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='followup_mode',
            field=models.CharField(choices=[('CALL', 'Call'), ('CALL_OUTGOING', 'Outgoing Call'), ('CALL_INCOMING', 'Incoming Call'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('VISIT', 'Visit'), ('OTHER', 'Other')], default='CALL', max_length=20),
        ),
    ]
