# Generated by Django 6.0.7 on 2026-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_alter_followup_followup_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='followup_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CALL_BACK', 'Call Back'), ('DNP', 'Do Not Pickup (DNP)'), ('NOT_CONNECTED', 'Not Connected'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
