# Generated by Django 6.0.7 on 2026-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_alter_followup_followup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='followup_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
