# Generated by Django 5.0.14 on 2026-08-11 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('campaign_id', models.CharField(blank=True, max_length=150)),
                ('ad_name', models.CharField(blank=True, max_length=150)),
                ('ad_set', models.CharField(blank=True, max_length=150)),
                ('landing_page', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Source categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='leads.sourcecategory')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('alternate_mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=150)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_type', models.CharField(blank=True, max_length=50)),
                ('temperature', models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], db_index=True, default='COLD', max_length=10)),
                ('deal_status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost'), ('HOLD', 'Hold')], db_index=True, default='OPEN', max_length=10)),
                ('admission_status', models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('INTERESTED', 'Interested'), ('APPLIED', 'Applied'), ('ADMISSION_DONE', 'Admission Done'), ('CANCELLED', 'Cancelled')], default='NOT_APPLIED', max_length=20)),
                ('inquiry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('ad_platform', models.CharField(blank=True, max_length=100)),
                ('campaign_id_text', models.CharField(blank=True, help_text='Raw campaign/ad id string if no Campaign record exists', max_length=150)),
                ('referral_type', models.CharField(blank=True, choices=[('STUDENT', 'Student Referral'), ('EMPLOYEE', 'Employee Referral'), ('PARTNER', 'Partner Referral'), ('OTHER', 'Other')], max_length=10)),
                ('referral_person', models.CharField(blank=True, max_length=150)),
                ('referral_contact', models.CharField(blank=True, max_length=50)),
                ('referral_notes', models.TextField(blank=True)),
                ('landing_page', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('original_utm_source', models.CharField(blank=True, editable=False, max_length=100)),
                ('original_utm_medium', models.CharField(blank=True, editable=False, max_length=100)),
                ('original_utm_campaign', models.CharField(blank=True, editable=False, max_length=100)),
                ('original_referral_person', models.CharField(blank=True, editable=False, max_length=150)),
                ('original_landing_page', models.CharField(blank=True, editable=False, max_length=255)),
                ('external_lead_id', models.CharField(blank=True, db_index=True, help_text='ID from external system (API/Website/Ad platform) — used to prevent duplicate auto-created leads', max_length=150)),
                ('raw_source_metadata', models.JSONField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('last_followup_date', models.DateField(blank=True, null=True)),
                ('followup_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('import_source_file', models.CharField(blank=True, max_length=255)),
                ('import_source_sheet', models.CharField(blank=True, max_length=100)),
                ('import_source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.campaign')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('original_campaign', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.campaign')),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource')),
                ('original_lead_source', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadsource')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstage')),
                ('original_source_category', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.sourcecategory')),
                ('source_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.sourcecategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='leads', to='leads.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile'], name='leads_lead_mobile_0244d4_idx'), models.Index(fields=['stage', 'temperature'], name='leads_lead_stage_i_30e0a2_idx'), models.Index(fields=['deal_status'], name='leads_lead_deal_st_899007_idx'), models.Index(fields=['inquiry_date'], name='leads_lead_inquiry_7b98b7_idx'), models.Index(fields=['next_followup_date'], name='leads_lead_next_fo_c0a69f_idx')],
            },
        ),
    ]
