# Generated by Django 6.0.6 on 2026-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='base_price',
            field=models.PositiveIntegerField(default=0, help_text='Base course fee in Rupees'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_discount',
            field=models.PositiveIntegerField(default=0, help_text='Maximum allowed discount in Rupees'),
        ),
    ]
