# Generated by Django 6.0.6 on 2026-08-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('leads', '0002_course_base_price_course_max_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_leads', to='imports.importjob'),
        ),
    ]
