# Generated by Django 6.0.6 on 2026-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_import_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='temperature',
            field=models.CharField(choices=[('UNCONTACTED', 'Uncontacted'), ('NOT_PICKED', 'Call Not Picked'), ('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold (Not Interested)')], db_index=True, default='UNCONTACTED', max_length=20),
        ),
    ]
