# Generated by Django 6.0.6 on 2026-08-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Purpose/usage of this master category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Group',
                'verbose_name_plural': 'Master Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='Optional short code or identifier', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leads.mastergroup')),
            ],
            options={
                'verbose_name': 'Master Item',
                'verbose_name_plural': 'Master Items',
                'ordering': ['order', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
    ]
