# Generated by Django 6.0.7 on 2026-08-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_mastergroup_masteritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NelsonLeadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nelson_dantoli', models.CharField(blank=True, max_length=150)),
                ('lead_received_time', models.TimeField(blank=True, null=True)),
                ('lead_calling_time', models.TimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('doctor', models.CharField(blank=True, max_length=150)),
                ('appo_book', models.CharField(blank=True, max_length=50)),
                ('appo_booked_date', models.DateField(blank=True, null=True)),
                ('calling_date_remark_1', models.DateField(blank=True, null=True)),
                ('remark_1', models.TextField(blank=True)),
                ('calling_time_remark_2', models.TimeField(blank=True, null=True)),
                ('calling_date_remark_2', models.DateField(blank=True, null=True)),
                ('remark_2', models.TextField(blank=True)),
                ('calling_date_remark_3', models.DateField(blank=True, null=True)),
                ('remark_3', models.TextField(blank=True)),
                ('done', models.CharField(blank=True, max_length=100)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('uhid_id_no', models.CharField(blank=True, max_length=100)),
                ('pharmacy_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opd_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ipd_no', models.CharField(blank=True, max_length=100)),
                ('investigation', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nelson_data', to='leads.lead')),
            ],
        ),
    ]
