# Generated by Django 6.0.7 on 2026-08-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospital_user_hospital'),
        ('leads', '0006_nelsonleaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.hospital'),
        ),
    ]
