# Generated by Django 6.0.7 on 2026-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
