# Generated by Django 6.0.7 on 2026-08-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_picture'),
        ('leads', '0009_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masteritem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_items', to='accounts.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='masteritem',
            unique_together={('group', 'name', 'hospital')},
        ),
    ]
