# Generated by Django 6.0.7 on 2026-08-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hospital_registration_no_hospital_settings'),
        ('leads', '0011_appointment_doctor_notes_appointment_doctor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.hospital'),
        ),
    ]
