# Generated by Django 6.0.7 on 2026-08-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hospital_registration_no_hospital_settings'),
        ('leads', '0012_campaign_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field Identifier / Slug (e.g. guardian_name)', max_length=100)),
                ('label', models.CharField(help_text='Label displayed on form (e.g. Guardian Name)', max_length=150)),
                ('field_type', models.CharField(choices=[('TEXT', 'Single Line Text'), ('NUMBER', 'Number / Integer'), ('DECIMAL', 'Currency / Decimal'), ('DATE', 'Date Picker'), ('DROPDOWN', 'Dropdown (Select List)'), ('TEXTAREA', 'Multi-line Text (Textarea)'), ('CHECKBOX', 'Checkbox (Yes / No)')], default='TEXT', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for Dropdown type (e.g. Option 1, Option 2)')),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_form_fields', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'Lead Custom Field',
                'verbose_name_plural': 'Lead Custom Fields',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
