# Generated by Django 6.0.7 on 2026-08-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_leadcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcustomfield',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True if this is a core standard field'),
        ),
    ]
