# Generated by Django 6.0.7 on 2026-08-22 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hospital_registration_no_hospital_settings'),
        ('leads', '0014_leadcustomfield_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('is_main_branch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Branch',
                'verbose_name_plural': 'Hospital Branches',
                'ordering': ['order', 'name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DoctorBranchAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text="e.g. ['Monday', 'Tuesday', 'Wednesday']")),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=15)),
                ('max_patients_per_slot', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to='leads.hospitalbranch')),
            ],
            options={
                'verbose_name': 'Doctor Branch Availability',
                'verbose_name_plural': 'Doctor Branch Availabilities',
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='departments', to='leads.hospitalbranch')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Department',
                'verbose_name_plural': 'Hospital Departments',
                'ordering': ['order', 'name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HospitalDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='leads.hospitaldepartment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'Disease / Condition',
                'verbose_name_plural': 'Diseases & Conditions',
                'ordering': ['order', 'name'],
                'unique_together': {('hospital', 'department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HospitalDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associated_diseases', models.ManyToManyField(blank=True, related_name='doctors', to='leads.hospitaldisease')),
                ('branches', models.ManyToManyField(blank=True, related_name='doctors', through='leads.DoctorBranchAvailability', to='leads.hospitalbranch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='leads.hospitaldepartment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctors', to='accounts.hospital')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order', 'name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.AddField(
            model_name='doctorbranchavailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='leads.hospitaldoctor'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorbranchavailability',
            unique_together={('doctor', 'branch')},
        ),
    ]
