# Generated by Django 6.0.7 on 2026-08-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_hospitalbranch_doctorbranchavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctor',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='leads.hospitaldepartment'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='leads.hospitaldepartment'),
        ),
    ]
