# Generated by Django 6.0.7 on 2026-08-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hospital_is_active'),
        ('leads', '0016_hospitaldoctor_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.hospital'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('hospital', 'name')},
        ),
    ]
