# Generated by Django 6.0.7 on 2026-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_course_hospital_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.CharField(blank=True, help_text='Batch Name / Code (e.g. Batch A, Morning Batch, Full-Stack Python June)', max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='batch_time',
            field=models.CharField(blank=True, help_text='Batch Timing (e.g. 10:00 AM - 12:00 PM)', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.CharField(blank=True, help_text='Tutor / Trainer / Instructor Name', max_length=150),
        ),
    ]
