# Generated by Django 6.0.7 on 2026-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_course_batch_course_batch_time_course_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
