# Generated by Django 6.0.7 on 2026-09-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_course_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='temperature',
            field=models.CharField(choices=[('UNCONTACTED', 'Uncontacted'), ('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('FREEZE', 'Freeze'), ('NOT_PICKED', 'Call Not Picked')], db_index=True, default='UNCONTACTED', max_length=20),
        ),
    ]
