# Generated by Django 6.0.7 on 2026-10-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_alter_lead_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='business_type',
            field=models.CharField(choices=[('ALL', 'All / Shared'), ('HOSPITAL', 'Hospital Only'), ('ACADEMY', 'Academy Only')], db_index=True, default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='admission_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('HOLD', 'Hold'), ('WON', 'Won'), ('LOST', 'Lost')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='deal_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CONTACTED', 'Contacted'), ('WON', 'Won'), ('LOST', 'Lost'), ('HOLD', 'Hold')], db_index=True, default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='temperature',
            field=models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('FREEZE', 'Freeze')], db_index=True, default='HOT', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='leadstage',
            unique_together={('name', 'business_type')},
        ),
    ]
