# Generated by Django 6.0.7 on 2026-10-01 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_branch'),
        ('leads', '0021_leadstage_business_type_alter_lead_admission_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadstage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leadstage',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Specific hospital/business tenant. Null/None means global or Zappcode Academy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='accounts.hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='leadstage',
            unique_together={('hospital', 'name', 'business_type')},
        ),
    ]
