# Generated by Django 6.0.7 on 2026-10-06 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_hospital_options_hospital_business_code_and_more'),
        ('leads', '0022_alter_leadstage_unique_together_leadstage_hospital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('BOOKING', 'Booking Message'), ('FOLLOWUP', 'Follow-up Message')], db_index=True, max_length=20)),
                ('custom_text', models.TextField(blank=True, help_text='Custom template text with placeholders like {patient_name}, {hospital_name}, {branch_name}, {hospital_address}, {doctor_name}, {appointment_date}, {appointment_time}, {user_name}')),
                ('is_confirmed', models.BooleanField(default=False, help_text='True if user has confirmed using this custom template over system default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_messages', to='accounts.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Custom Message',
                'verbose_name_plural': 'User Custom Messages',
                'unique_together': {('user', 'message_type')},
            },
        ),
    ]
