# Generated by Django 6.0.7 on 2026-10-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_usercustommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommessage',
            name='message_type',
            field=models.CharField(choices=[('BOOKING', 'Booking Message'), ('FOLLOWUP', 'Follow-up Message'), ('BILLING', 'Billing / Thank You Message')], db_index=True, max_length=20),
        ),
    ]
