# Generated by Django 6.0.6 on 2026-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='extra_discount_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='max_allowed_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
