# Generated by Django 6.0.6 on 2026-08-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_extra_discount_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='course_status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DROPOUT', 'Dropout')], default='ONGOING', max_length=15),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_plan',
            field=models.CharField(choices=[('FULL', 'One-time Full Payment'), ('EMI', 'Installment / EMI Plan')], default='FULL', max_length=15),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('reminder_sent_count', models.PositiveIntegerField(default=0)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='admissions.admission')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
