# Generated by Django 6.0.6 on 2026-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admission_course_status_admission_payment_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='course_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('STARTED', 'Started'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DROPOUT', 'Dropout')], default='ONGOING', max_length=15),
        ),
    ]
