# Generated by Django 6.0.7 on 2026-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_admission_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='batch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='admission',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='emi_months',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='monthly_emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('ONE_TIME_CASH', 'One Time Cash'), ('ONE_TIME_UPI', 'One Time UPI'), ('EMI', 'EMI (Monthly Installments)')], default='ONE_TIME_UPI', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='tutor',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
