# Generated by Django 6.0.6 on 2026-08-14 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_admission_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
