# Generated by Django 5.0.14 on 2026-08-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetaAdsConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Nelson Hospital", max_length=100)),
                (
                    "page_access_token",
                    models.TextField(
                        help_text="Long-lived Page Access Token from Meta"
                    ),
                ),
                (
                    "ad_account_id",
                    models.CharField(
                        help_text="Ad Account ID (without act_ prefix)", max_length=100
                    ),
                ),
                (
                    "page_id",
                    models.CharField(help_text="Facebook Page ID", max_length=100),
                ),
                (
                    "webhook_verify_token",
                    models.CharField(
                        help_text="Secret token for webhook verification",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Meta Ads Connection",
            },
        ),
        migrations.CreateModel(
            name="MetaCampaignStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_id", models.CharField(max_length=100)),
                ("campaign_name", models.CharField(max_length=255)),
                ("date_preset", models.CharField(default="last_30d", max_length=50)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("leads_count", models.PositiveIntegerField(default=0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-spend"],
                "unique_together": {("campaign_id", "date_preset")},
            },
        ),
        migrations.CreateModel(
            name="MetaLeadForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_id", models.CharField(max_length=100, unique=True)),
                ("form_name", models.CharField(max_length=255)),
                ("is_syncing", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="meta_ads.metaadsconnection",
                    ),
                ),
            ],
        ),
    ]
