# Generated by Django 6.0.6 on 2026-08-11 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('calls_attended', models.PositiveIntegerField(default=0, verbose_name='Calls Attended')),
                ('leads_cold', models.PositiveIntegerField(default=0, verbose_name='Cold Leads')),
                ('calls_not_connected', models.PositiveIntegerField(default=0, verbose_name='Calls Not Connected')),
                ('other_updates', models.TextField(blank=True, verbose_name='Other Updates / Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('user', 'report_date')},
            },
        ),
    ]
