# Generated by Django 6.0.6 on 2026-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='admissions_done',
            field=models.PositiveIntegerField(default=0, verbose_name='Admissions Done Today'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='challenges_faced',
            field=models.TextField(blank=True, verbose_name='Challenges Faced'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='follow_ups_pending',
            field=models.PositiveIntegerField(default=0, verbose_name='Follow-ups Pending'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='incoming_calls',
            field=models.PositiveIntegerField(default=0, verbose_name='Incoming Calls Received'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='key_highlight',
            field=models.CharField(blank=True, max_length=300, verbose_name='Key Highlight / Achievement'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='leads_interested',
            field=models.PositiveIntegerField(default=0, verbose_name='Interested Leads'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='leads_visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads Who Visited'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='mood_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '😞 Very Low'), (2, '😕 Low'), (3, '😐 Okay'), (4, '🙂 Good'), (5, '😄 Excellent')], default=3, verbose_name='Energy / Mood Rating'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='outgoing_calls',
            field=models.PositiveIntegerField(default=0, verbose_name='Outgoing Calls Made'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='tomorrow_priority',
            field=models.TextField(blank=True, verbose_name="Tomorrow's Priority / Plan"),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='calls_attended',
            field=models.PositiveIntegerField(default=0, verbose_name='Calls Attended (Total)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='leads_cold',
            field=models.PositiveIntegerField(default=0, verbose_name='Cold Leads (Not Interested)'),
        ),
    ]
