# Generated by Django 6.0.7 on 2026-08-20 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailyreport_admissions_done_and_more'),
        ('leads', '0010_alter_masteritem_unique_together_masteritem_hospital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, verbose_name='Task Details')),
                ('due_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Due Date')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='Due Time / Reminder Time')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent / Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sync_to_followup', models.BooleanField(default=False, verbose_name='Sync as Follow-up on Lead')),
                ('is_reported_to_admin', models.BooleanField(default=False, verbose_name='Reported to Admin')),
                ('admin_report_notes', models.TextField(blank=True, verbose_name='Report Summary sent to Admin')),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date', 'due_time', '-created_at'],
            },
        ),
    ]
