# Generated by Django 6.0.6 on 2026-08-14 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailyreport_admissions_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
