# Generated by Django 6.0.7 on 2026-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_taskreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='appointments_booked',
            field=models.PositiveIntegerField(default=0, verbose_name='Appointments Booked / Approved'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='first_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Login Time'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='follow_ups_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='Follow-ups Taken Today'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='freeze_leads',
            field=models.PositiveIntegerField(default=0, verbose_name='Freeze Leads (Cancelled / Not Interested)'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='last_logout_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Logout Time'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='leads_assigned',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads Assigned Today'),
        ),
    ]
