# Generated by Django 6.0.7 on 2026-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dailyreport_appointments_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='fees_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fees Payments Collected (₹)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='admissions_done',
            field=models.PositiveIntegerField(default=0, verbose_name='Admissions Completed Today'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='leads_visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Student Visits (Leads Visited)'),
        ),
    ]
