# Generated by Django 6.0.7 on 2026-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dailyreport_fees_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='mood',
            field=models.CharField(choices=[('Great', '😄 Great'), ('Good', '🙂 Good'), ('Moderate', '😐 Moderate'), ('Tired', '🥱 Tired'), ('Exhausted', '😫 Exhausted'), ('Sick', '🤒 Sick')], default='Good', max_length=30, verbose_name="Today's Mood"),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='payments_done',
            field=models.PositiveIntegerField(default=0, verbose_name='Payments Done Count'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='pending_leads',
            field=models.PositiveIntegerField(default=0, verbose_name='Pending Leads'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='tomorrow_followups',
            field=models.PositiveIntegerField(default=0, verbose_name="Tomorrow's Follow-ups"),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='mood_rating',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Energy / Mood Rating'),
        ),
    ]
