# Generated by Django 6.0.7 on 2026-10-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dailyreport_mood_dailyreport_payments_done_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskreminder',
            options={'ordering': ['-due_date', 'due_time', '-created_at']},
        ),
    ]
