# Generated by Django 6.0.6 on 2026-08-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('COUNSELLOR', 'Counsellor'), ('HR', 'HR')], default='COUNSELLOR', max_length=20),
        ),
    ]
