# Generated by Django 6.0.7 on 2026-08-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospital_user_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('GYNAEC', 'GYNAEC'), ('NEUROLOGY', 'NEUROLOGY'), ('NEURO SURGERY', 'NEURO SURGERY'), ('PED.NEUROLOGY', 'PED.NEUROLOGY'), ('PEDIATRIC', 'PEDIATRIC'), ('OPTHALMOLOGY', 'OPTHALMOLOGY'), ('ORTHOPEDICS', 'ORTHOPEDICS'), ('GASTROLOGY', 'GASTROLOGY'), ('PEDIATRIC NEPHROLOGOGIST', 'PEDIATRIC NEPHROLOGOGIST'), ('PED.SURGERY', 'PED.SURGERY'), ('CARDIAC SURGERY', 'CARDIAC SURGERY'), ('PLASTIC SURGERY', 'PLASTIC SURGERY'), ('GENRAL SURGERY', 'GENRAL SURGERY'), ('GENERAL MEDICINE', 'GENERAL MEDICINE'), ('UROLOGY', 'UROLOGY'), ('PHYSIOTHERAPY', 'PHYSIOTHERAPY'), ('ENT', 'ENT'), ('DERMATOLOGIST', 'DERMATOLOGIST')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Surgeon', 'Surgeon'), ('Physician', 'Physician'), ('Pediatrician', 'Pediatrician'), ('Gynecologist', 'Gynecologist'), ('Neurologist', 'Neurologist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Orthopedist', 'Orthopedist'), ('ENT Specialist', 'ENT Specialist'), ('Physiotherapist', 'Physiotherapist'), ('Urologist', 'Urologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD_ATTENDENT', 'Lead Attendent'), ('DOCTOR', 'Doctor')], default='LEAD_ATTENDENT', max_length=20),
        ),
    ]
