# Generated by Django 6.0.7 on 2026-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_department_user_speciality_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD_ATTENDENT', 'Lead Attendent'), ('DOCTOR', 'Doctor'), ('HR', 'HR'), ('COUNSELLOR', 'Counsellor')], default='LEAD_ATTENDENT', max_length=20),
        ),
    ]
