# Generated by Django 6.0.7 on 2026-08-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='HospitalRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD_ATTENDENT', 'Lead Attendent'), ('DOCTOR', 'Doctor'), ('HR', 'HR'), ('COUNSELLOR', 'Counsellor')], max_length=50)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'role')},
            },
        ),
    ]
