# Generated by Django 6.0.7 on 2026-08-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_custom_permissions_hospitalrolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='registration_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
