# Generated by Django 6.0.7 on 2026-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hospital_registration_no_hospital_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status of this business/tenant'),
        ),
    ]
