# Generated by Django 6.0.7 on 2026-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_hospital_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text="List of roles enabled for this business/tenant (e.g. ['ADMIN', 'MANAGER', 'LEAD_ATTENDENT', 'DOCTOR'])"),
        ),
    ]
