# Generated by Django 6.0.7 on 2026-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hospital_allowed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalrolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD_ATTENDENT', 'Lead Attendant'), ('DOCTOR', 'Doctor'), ('HR', 'HR'), ('COUNSELLOR', 'Counsellor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD_ATTENDENT', 'Lead Attendant'), ('DOCTOR', 'Doctor'), ('HR', 'HR'), ('COUNSELLOR', 'Counsellor')], default='LEAD_ATTENDENT', max_length=20),
        ),
    ]
