# Generated by Django 6.0.7 on 2026-09-25 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_hospitalrolepermission_role_alter_user_role'),
        ('leads', '0020_alter_lead_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Assigned Branch for Branch Managers, Telecallers, and Doctors. Null/Empty means All Branches (Full Business Access).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='leads.hospitalbranch'),
        ),
    ]
