# Generated by Django 6.0.7 on 2026-10-05 14:17

from django.db import migrations, models

def populate_business_codes(apps, schema_editor):
    Hospital = apps.get_model('accounts', 'Hospital')
    for h in Hospital.objects.all():
        name_lower = (h.name or '').lower()
        if 'hospital' in name_lower or 'clinic' in name_lower or 'medical' in name_lower or 'nelson' in name_lower:
            h.industry = 'HOSPITAL'
            h.business_code = f"BIZ-HOSP-{h.id:03d}"
        else:
            h.industry = 'ACADEMY'
            h.business_code = f"BIZ-ACAD-{h.id:03d}"
        h.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_hospital_options_alter_user_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AddField(
            model_name='hospital',
            name='business_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique Business ID / Code (e.g. BIZ-HOSP-001, BIZ-ACAD-002)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='industry',
            field=models.CharField(choices=[('HOSPITAL', 'Healthcare / Hospital / Clinic'), ('ACADEMY', 'Education / Academy / Coaching'), ('IT_SERVICES', 'IT Services / Software Agency'), ('REAL_ESTATE', 'Real Estate / Builders'), ('OTHER', 'Other / General Business')], db_index=True, default='ACADEMY', help_text='Industry category for this business', max_length=50),
        ),
        migrations.RunPython(populate_business_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='hospital',
            name='business_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique Business ID / Code (e.g. BIZ-HOSP-001, BIZ-ACAD-002)', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
