from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
    path("", views.lead_list, name="lead_list"),
    path("appointments-done/", views.appointments_done_list, name="appointments_done"),
    path("payment-done/", views.payment_done_list, name="payment_done"),
    path("pending-leads/", views.pending_leads, name="pending_leads"),
    path("my-leads/", views.my_leads, name="my_leads"),
    path("lost-leads/", views.lost_leads, name="lost_leads"),
    path("team-history/", views.team_history, name="team_history"),
    path("team-history/<int:user_id>/analysis/", views.user_performance_analysis, name="user_performance_analysis"),
    path("add/", views.lead_add, name="lead_add"),
    path("api/check-mobile/", views.check_duplicate_mobile, name="check_duplicate_mobile"),
    path("api/check-uhid/", views.check_duplicate_uhid, name="check_duplicate_uhid"),
    path("api/doctor-slots/", views.doctor_slots_api, name="doctor_slots_api"),
    path("<int:pk>/", views.lead_detail, name="lead_detail"),
    path("<int:pk>/edit/", views.lead_edit, name="lead_edit"),
    path("<int:pk>/self-assign/", views.lead_self_assign, name="lead_self_assign"),
    path("<int:pk>/book-appointment/", views.book_appointment, name="book_appointment"),
    path("<int:pk>/assign/", views.assign_lead, name="assign_lead"),
    path("<int:pk>/archive/", views.lead_archive, name="lead_archive"),
    path("<int:pk>/add-note/", views.add_note, name="add_note"),
    path("<int:pk>/add-followup/", views.add_followup, name="add_followup"),
    path("<int:pk>/followup/<int:fu_id>/update/", views.update_followup_status, name="update_followup_status"),
    path("<int:pk>/quick-update-stage/", views.lead_quick_update_stage, name="lead_quick_update_stage"),
    path("<int:pk>/update-admission-status/", views.update_admission_status, name="update_admission_status"),
    path("<int:pk>/convert-admission/", views.convert_admission, name="convert_admission"),
    path("bulk-action/", views.bulk_action, name="bulk_action"),
    path("archived/", views.archived_leads, name="archived_leads"),
    path("duplicates/", views.duplicates, name="duplicates"),
    path("duplicates/<int:pk>/delete/", views.duplicate_lead_delete, name="duplicate_lead_delete"),
    path("duplicates/merge/", views.duplicate_leads_merge, name="duplicate_leads_merge"),
    path("masters/", views.masters, name="masters"),
    path("course-master/", views.course_master, name="course_master"),
    path("course-master/import/", views.course_excel_import, name="course_excel_import"),
    path("course-master/sample-download/", views.course_sample_download, name="course_sample_download"),
    path("masters/course/<int:pk>/edit/", views.course_edit, name="course_edit"),
    path("masters/course/<int:pk>/archive/", views.course_archive, name="course_archive"),
    path("masters/<str:kind>/<int:pk>/toggle/", views.master_toggle, name="master_toggle"),

    # Universal Master System routes
    path("universal-masters/", views.universal_master_list, name="universal_masters"),
    path("universal-masters/group/add/", views.master_group_add, name="master_group_add"),
    path("universal-masters/group/<int:pk>/edit/", views.master_group_edit, name="master_group_edit"),
    path("universal-masters/group/<int:pk>/delete/", views.master_group_delete, name="master_group_delete"),
    path("universal-masters/item/add/", views.master_item_add, name="master_item_add"),
    path("universal-masters/item/<int:pk>/edit/", views.master_item_edit, name="master_item_edit"),
    path("universal-masters/item/<int:pk>/toggle/", views.master_item_toggle, name="master_item_toggle"),
    path("universal-masters/item/<int:pk>/delete/", views.master_item_delete, name="master_item_delete"),
    # Temperature Manager route
    path("temperature-manager/", views.temperature_manager, name="temperature_manager"),
    path("custom-messages/", views.custom_message_manager, name="custom_message_manager"),

    # Dynamic Lead Custom Form Fields routes
    path("universal-masters/custom-fields/add/", views.custom_field_add, name="custom_field_add"),
    path("universal-masters/custom-fields/<int:pk>/edit/", views.custom_field_edit, name="custom_field_edit"),
    path("universal-masters/custom-fields/<int:pk>/toggle/", views.custom_field_toggle, name="custom_field_toggle"),
    path("universal-masters/custom-fields/<int:pk>/delete/", views.custom_field_delete, name="custom_field_delete"),

    # Hospital Master Configuration & Cascading Routes
    path("hospital-configuration/", views.hospital_configuration_view, name="hospital_configuration"),
    path("hospital-configuration/profile/save/", views.hospital_profile_save, name="hospital_profile_save"),
    path("hospital-configuration/import/", views.hospital_master_excel_import, name="hospital_master_excel_import"),
    path("hospital-configuration/sample-download/", views.hospital_master_sample_download, name="hospital_master_sample_download"),
    path("hospital-configuration/export/excel/", views.export_hospital_config_excel, name="hospital_config_export_excel"),
    path("hospital-configuration/export/pdf/", views.export_hospital_config_pdf, name="hospital_config_export_pdf"),
    path("hospital-configuration/branch/save/", views.hospital_branch_save, name="hospital_branch_create"),
    path("hospital-configuration/branch/<int:pk>/save/", views.hospital_branch_save, name="hospital_branch_edit"),
    path("hospital-configuration/branch/<int:pk>/toggle/", views.hospital_branch_toggle, name="hospital_branch_toggle"),
    path("hospital-configuration/branch/<int:pk>/delete/", views.hospital_branch_delete, name="hospital_branch_delete"),
    path("hospital-configuration/department/save/", views.hospital_department_save, name="hospital_department_create"),
    path("hospital-configuration/department/<int:pk>/save/", views.hospital_department_save, name="hospital_department_edit"),
    path("hospital-configuration/department/<int:pk>/toggle/", views.hospital_department_toggle, name="hospital_department_toggle"),
    path("hospital-configuration/department/<int:pk>/delete/", views.hospital_department_delete, name="hospital_department_delete"),
    path("hospital-configuration/disease/save/", views.hospital_disease_save, name="hospital_disease_create"),
    path("hospital-configuration/disease/<int:pk>/save/", views.hospital_disease_save, name="hospital_disease_edit"),
    path("hospital-configuration/disease/<int:pk>/toggle/", views.hospital_disease_toggle, name="hospital_disease_toggle"),
    path("hospital-configuration/disease/<int:pk>/delete/", views.hospital_disease_delete, name="hospital_disease_delete"),
    path("hospital-configuration/doctor/save/", views.hospital_doctor_save, name="hospital_doctor_create"),
    path("hospital-configuration/doctor/<int:pk>/save/", views.hospital_doctor_save, name="hospital_doctor_edit"),
    path("hospital-configuration/doctor/<int:pk>/toggle/", views.hospital_doctor_toggle, name="hospital_doctor_toggle"),
    path("hospital-configuration/doctor/<int:pk>/delete/", views.hospital_doctor_delete, name="hospital_doctor_delete"),
    path("api/cascading-hospital-data/", views.cascading_hospital_data_api, name="cascading_hospital_data_api"),
    path("bulk-transfer/", views.bulk_lead_transfer, name="bulk_lead_transfer"),
]

